
langchain4j:
  open-ai:
    chat-model:
      api-key: sk-f040796ae0bd4e8c9c81dc462aae0c70
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-max
      log-requests: true
      log-responses: true
      max-retries: 3
    streaming-chat-model:
      api-key: sk-f040796ae0bd4e8c9c81dc462aae0c70
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-max
      log-requests: true
      log-responses: true
      max-retries: 3
    embedding-model:
      api-key: sk-f040796ae0bd4e8c9c81dc462aae0c70
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v4
      log-requests: true
      log-responses: true
      max-retries: 3

bigmodel:
  api-key: 4b870e36dbc3480e9d5cd9974e3c79dc.XNjVY86m0TejXPYl
# 搜索API配置
search:
  api:
    key: 123 # 请在此处配置您的SearchAPI密钥
    engine: google # 搜索引擎，可选: google, bing, baidu等

spring:
  data:
    redis:
      port: 6379
      host: 152.136.36.48
      password: fbx@123456
      database: 1
  datasource:
    url: jdbc:mysql://152.136.36.48:3306/fbx?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: root
    password: fbx@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 连接超时配置
      time-between-eviction-runs-millis: 60000 # 检查间隔(ms)
      min-evictable-idle-time-millis: 300000   # 最小空闲时间(ms)
      max-evictable-idle-time-millis: 900000   # 最大空闲时间(ms)
      init:
        enabled: true
#mybatis-plus:
#  type-aliases-package: com.mk.springlangchain4j.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
